<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SemanticSearch\DotNet\SemanticSearch.DotNet.csproj" />
    <ProjectReference Include="..\..\RAG\DotNet\RAG.DotNet.csproj" />
    <ProjectReference Include="..\..\..\services\Services.DotNet\Services.DotNet.csproj" />
  </ItemGroup>

</Project>
