from __future__ import annotations

import json
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Iterable

def schedule_batch_prep(
    food_dir: Path,
    recipes_to_prepare: list[int] | None = None,
    freezer_capacity: int = 10,
    output_path: Path | None = None,
    markdown_path: Path | None = None,
) -> tuple[Path, Path | None]:
    """Calculate optimal batch cooking schedule based on freezer capacity and recipe requirements.

    Args:
        food_dir: Path to the food directory
        recipes_to_prepare: List of recipe IDs to include in schedule (all if None)
        freezer_capacity: Number of portions that can be prepared at once
        output_path: Optional output path for JSON schedule
        markdown_path: Optional output path for markdown schedule

    Returns:
        Tuple of (JSON output path, markdown output path)
    """
    food_dir = food_dir.resolve()
    if output_path is None:
        output_path = food_dir / "batch_schedule.json"
    else:
        output_path = output_path.resolve()

    if markdown_path is None:
        markdown_path = food_dir / "batch_schedule.md"
    else:
        markdown_path = markdown_path.resolve()
    
    # Get database path from data directory
    db_path = Path(__file__).resolve().parents[3] / "data" / "recipes_local.db"
    
    # Connect to SQLite database
    conn = sqlite3.connect(db_path)
    
    try:
        schedule = {
            "generated_by": "batch_preparation_scheduler.py",
            "schedule_date": datetime.now().isoformat(),
            "freezer_capacity": freezer_capacity,
            "batches": [],
        }

        # Get all recipes with their details
        cursor = conn.execute("""
            SELECT id, name, servings, time_to_prepare, tags
            FROM recipes 
            ORDER BY name
        """)
        
        all_recipes = []
        for row in cursor.fetchall():
            recipe_id, name, servings, time_to_prepare, tags = row
            all_recipes.append({
                "id": recipe_id,
                "name": name,
                "servings": servings or 1,
                "time_to_prepare": time_to_prepare or 0,
                "tags": tags.split(",") if tags else []
            })
        
        # If no recipes specified, prepare all
        if recipes_to_prepare is None:
            recipe_ids = [r["id"] for r in all_recipes]
        else:
            recipe_ids = recipes_to_prepare
            
        # Filter to only include recipes that exist
        available_recipes = [r for r in all_recipes if r["id"] in recipe_ids]
        
        # Sort by preparation time (longest first) for efficient scheduling
        available_recipes.sort(key=lambda r: r["time_to_prepare"], reverse=True)
        
        batches = []
        current_batch = []
        current_time = 0
        total_servings = 0
        
        # Group recipes into batches based on freezer capacity
        for recipe in available_recipes:
            # Simple batching algorithm - add to current batch if it fits
            if len(current_batch) < freezer_capacity:
                current_batch.append(recipe)
                total_servings += recipe["servings"]
            else:
                # Start a new batch
                batches.append({
                    "batch_id": len(batches) + 1,
                    "recipes": current_batch.copy(),
                    "total_servings": sum(r["servings"] for r in current_batch),
                    "estimated_time": sum(r["time_to_prepare"] for r in current_batch),
                    "start_time": current_time
                })
                current_batch = [recipe]
                total_servings = recipe["servings"]
                current_time += 30  # Add some buffer time between batches
        
        # Don't forget the last batch
        if current_batch:
            batches.append({
                "batch_id": len(batches) + 1,
                "recipes": current_batch,
                "total_servings": sum(r["servings"] for r in current_batch),
                "estimated_time": sum(r["time_to_prepare"] for r in current_batch),
                "start_time": current_time
            })
        
        schedule["batches"] = batches

        # Write JSON output
        output_path.write_text(json.dumps(schedule, indent=2) + "\n", encoding="utf-8")

        # Write markdown summary
        lines = [
            "# Batch Preparation Schedule",
            "",
            f"Generated by: batch_preparation_scheduler.py",
            f"Freezer Capacity: {freezer_capacity} portions per batch",
            "",
        ]
        
        for batch in schedule["batches"]:
            lines.append(f"## Batch {batch['batch_id']}")
            lines.append(f"- **Estimated time**: {batch['estimated_time']} minutes")
            lines.append(f"- **Total servings**: {batch['total_servings']}")
            lines.append("Recipes:")
            for recipe in batch['recipes']:
                lines.append(f"  - {recipe['name']} ({recipe['servings']} servings)")
            lines.append("")
            
        markdown_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    finally:
        conn.close()

    return output_path, markdown_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Schedule batch cooking sessions based on freezer capacity.")
    parser.add_argument(
        "--food-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "food",
        help="Path to the food directory to scan",
    )
    parser.add_argument(
        "--recipes",
        type=int,
        nargs="+",
        help="List of recipe IDs to include in scheduling (all if not specified)",
    )
    parser.add_argument(
        "--freezer-capacity",
        type=int,
        default=10,
        help="Number of portions that can be prepared at once",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output path for the generated JSON schedule",
    )
    parser.add_argument(
        "--markdown-output",
        type=Path,
        default=None,
        help="Optional output path for the generated markdown schedule",
    )
    args = parser.parse_args()

    output_path, markdown_path = schedule_batch_prep(
        args.food_dir,
        args.recipes,
        args.freezer_capacity,
        args.output,
        args.markdown_output,
    )
    print(f"Batch preparation schedule written to {output_path}")
    if markdown_path is not None:
        print(f"Batch preparation schedule markdown written to {markdown_path}")