from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Iterable

IGNORED_DIRECTORIES = {"guides", "templates"}


def _is_recipe_file(path: Path) -> bool:
    if not path.is_file():
        return False
    if path.name.lower() == "readme.md":
        return False
    if path.name.lower().endswith("_template.md"):
        return False
    if path.suffix.lower() != ".md":
        return False
    return True


def _iter_recipe_files(food_dir: Path) -> Iterable[Path]:
    for category_dir in sorted(food_dir.iterdir()):
        if not category_dir.is_dir():
            continue
        if category_dir.name.startswith("."):
            continue
        if category_dir.name.lower() in IGNORED_DIRECTORIES:
            continue
        for path in sorted(category_dir.iterdir()):
            if _is_recipe_file(path):
                yield path


def build_recipe_index(food_dir: Path, output_path: Path | None = None, markdown_path: Path | None = None) -> tuple[Path, Path | None]:
    food_dir = food_dir.resolve()
    if output_path is None:
        output_path = food_dir / "recipe_index.json"
    else:
        output_path = output_path.resolve()

    if markdown_path is None:
        markdown_path = food_dir / "recipe_index.md"
    else:
        markdown_path = markdown_path.resolve()
    
    # Get database path from data directory
    db_path = Path(__file__).resolve().parents[3] / "data" / "recipes_local.db"
    
    # Connect to SQLite database
    conn = sqlite3.connect(db_path)
    
    try:
        sections: dict[str, list[dict[str, int | str]]] = {}
        
        # Get all recipes from database with their IDs
        cursor = conn.execute("""
            SELECT id, name, source_path, tags, servings, time_to_prepare, 
                   prepping, freezing_notes, reheat_notes, combinations, notes
            FROM recipes
            ORDER BY name
        """)
        
        for row in cursor.fetchall():
            recipe_id, name, source_path, tags, servings, time_to_prepare, \
                prepping, freezing_notes, reheat_notes, combinations, notes = row
            
            # Extract category from file path
            if source_path:
                category_name = Path(source_path).parent.name
            else:
                category_name = "unknown"
                
            sections.setdefault(category_name, []).append(
                {
                    "id": recipe_id,
                    "title": name,
                    "path": source_path,
                    "filename": Path(source_path).name if source_path else "",
                    "category": category_name,
                }
            )

        payload = {
            "generated_by": "generate_recipe_index.py",
            "food_dir": food_dir.as_posix(),
            "categories": [
                {"name": category, "recipes": sections[category]}
                for category in sorted(sections)
            ],
        }

        output_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

        lines = ["# Recipe Index", "", "This file is generated by the recipe index script.", ""]
        for category in payload["categories"]:
            lines.append(f"## {category['name'].capitalize()}")
            lines.append("")
            for recipe in category["recipes"]:
                lines.append(f"- [{recipe['title']}]({recipe['path']})")
            lines.append("")

        markdown_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    finally:
        conn.close()

    return output_path, markdown_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate a simple recipe index from markdown recipe files.")
    parser.add_argument(
        "--food-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "food",
        help="Path to the food directory to scan",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output path for the generated JSON index",
    )
    parser.add_argument(
        "--markdown-output",
        type=Path,
        default=None,
        help="Optional output path for the generated markdown index",
    )
    args = parser.parse_args()

    output_path, markdown_path = build_recipe_index(args.food_dir, args.output, args.markdown_output)
    print(f"Recipe index JSON written to {output_path}")
    if markdown_path is not None:
        print(f"Recipe index markdown written to {markdown_path}")
