from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


def _normalized_hash(payload: dict[str, Any]) -> str:
    blob = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


def _sql_value(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def _insert_statement(table: str, columns: list[str], rows: list[list[Any]]) -> str:
    if not rows:
        return f"-- no rows for {table}\n"

    rendered_rows = []
    for row in rows:
        rendered_rows.append("(" + ", ".join(_sql_value(value) for value in row) + ")")

    return (
        f"INSERT OR REPLACE INTO {table} ({', '.join(columns)}) VALUES\n"
        + ",\n".join(rendered_rows)
        + ";\n"
    )


def build_seed_sql(metadata: dict[str, Any]) -> str:
    recipe_id = int(metadata["recipe_id"])
    updated_at_utc = str(metadata["updated_at_utc"])
    provenance = str(metadata.get("provenance") or "phase3-seed-generator")

    recipe_rows: list[list[Any]] = []
    for translation in sorted(metadata.get("recipe_translations", []), key=lambda item: str(item["language"])):
        language = str(translation["language"]).strip()
        name = str(translation["name"]).strip()
        tags = (translation.get("tags") or "").strip() or None
        notes = (translation.get("notes") or "").strip() or None
        prepping = (translation.get("prepping") or "").strip() or None
        version = int(translation.get("translation_version", 1))

        content_hash = _normalized_hash(
            {
                "recipe_id": recipe_id,
                "language": language,
                "name": name,
                "tags": tags,
                "notes": notes,
                "prepping": prepping,
                "translation_version": version,
            }
        )

        recipe_rows.append(
            [
                recipe_id,
                language,
                name,
                tags,
                notes,
                prepping,
                version,
                content_hash,
                provenance,
                updated_at_utc,
            ]
        )

    ingredient_rows: list[list[Any]] = []
    ingredient_translations = sorted(
        metadata.get("ingredient_translations", []),
        key=lambda item: (int(item["ingredient_id"]), str(item["language"])),
    )
    for translation in ingredient_translations:
        ingredient_id = int(translation["ingredient_id"])
        language = str(translation["language"]).strip()
        name = str(translation["name"]).strip()
        unit = (translation.get("unit") or "").strip() or None
        version = int(translation.get("translation_version", 1))

        content_hash = _normalized_hash(
            {
                "ingredient_id": ingredient_id,
                "language": language,
                "name": name,
                "unit": unit,
                "translation_version": version,
            }
        )

        ingredient_rows.append(
            [
                ingredient_id,
                language,
                name,
                unit,
                version,
                content_hash,
                provenance,
                updated_at_utc,
            ]
        )

    index_metadata = metadata.get("index_metadata") or {}
    language_coverage = index_metadata.get("language_coverage") or sorted(
        {str(translation["language"]).strip() for translation in metadata.get("recipe_translations", [])}
    )
    language_coverage_value = ",".join(language_coverage)
    schema_version = str(index_metadata.get("projection_schema_version") or "phase3-localized-seed-v1")
    fingerprint_payload = {
        "recipe_id": recipe_id,
        "language_coverage": language_coverage,
        "schema_version": schema_version,
        "translations": recipe_rows,
        "ingredient_translations": ingredient_rows,
    }
    projection_fingerprint = str(index_metadata.get("projection_fingerprint") or _normalized_hash(fingerprint_payload))

    index_rows = [
        [
            recipe_id,
            language_coverage_value,
            projection_fingerprint,
            schema_version,
            updated_at_utc,
        ]
    ]

    sections = [
        "-- generated by src/scripts/recipes/generate_localization_seed.py",
        "-- do not edit by hand; update localization metadata json and regenerate",
        "",
        _insert_statement(
            "recipe_translations",
            [
                "recipe_id",
                "language",
                "name",
                "tags",
                "notes",
                "prepping",
                "translation_version",
                "content_hash",
                "provenance",
                "updated_at_utc",
            ],
            recipe_rows,
        ).rstrip(),
        "",
        _insert_statement(
            "ingredient_translations",
            [
                "ingredient_id",
                "language",
                "name",
                "unit",
                "translation_version",
                "content_hash",
                "provenance",
                "updated_at_utc",
            ],
            ingredient_rows,
        ).rstrip(),
        "",
        _insert_statement(
            "recipe_index_metadata",
            [
                "recipe_id",
                "language_coverage",
                "projection_fingerprint",
                "projection_schema_version",
                "projection_generated_at_utc",
            ],
            index_rows,
        ).rstrip(),
        "",
    ]

    return "\n".join(sections)


def generate_seed(metadata_path: Path, output_path: Path) -> str:
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    sql = build_seed_sql(metadata)
    output_path.write_text(sql, encoding="utf-8")
    return sql


def check_seed(metadata_path: Path, output_path: Path) -> bool:
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    expected = build_seed_sql(metadata)
    if not output_path.exists():
        return False
    actual = output_path.read_text(encoding="utf-8")
    return expected == actual


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate deterministic localization seed SQL from recipe localization metadata.")
    parser.add_argument(
        "--metadata",
        type=Path,
        default=Path(__file__).resolve().parents[3] / "data" / "food" / "proteins" / "salsa_verde_chicken.localization.json",
        help="Localization metadata JSON file path",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[3] / "data" / "food" / "proteins" / "salsa_verde_chicken.localization.seed.sql",
        help="Output SQL file path",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check for deterministic drift without writing",
    )
    args = parser.parse_args()

    metadata_path = args.metadata.resolve()
    output_path = args.output.resolve()

    if args.check:
        is_deterministic = check_seed(metadata_path, output_path)
        if is_deterministic:
            print("seed_drift_check: clean")
            return

        print("seed_drift_check: drift_detected")
        raise SystemExit(1)

    generate_seed(metadata_path, output_path)
    print(f"localization_seed_written: {output_path}")


if __name__ == "__main__":
    main()
