from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Iterable

IGNORED_DIRECTORIES = {"guides", "templates"}
REQUIRED_METADATA = ["Tags", "Tempo", "Porções"]
REQUIRED_SECTIONS = [
    "## 🧾 Ingredientes",
    "## 👨‍🍳 Preparação",
    "## ❄️ Congelação",
    "## 🔥 Reaquecimento",
    "## 🔄 Combinações",
    "## 💡 Notas",
]


def _is_recipe_file(path: Path) -> bool:
    if not path.is_file():
        return False
    if path.name.lower() == "readme.md":
        return False
    if path.name.lower().endswith("_template.md"):
        return False
    if path.suffix.lower() != ".md":
        return False
    return True


def _iter_recipe_files(food_dir: Path) -> Iterable[Path]:
    for category_dir in sorted(food_dir.iterdir()):
        if not category_dir.is_dir():
            continue
        if category_dir.name.startswith("."):
            continue
        if category_dir.name.lower() in IGNORED_DIRECTORIES:
            continue
        for path in sorted(category_dir.iterdir()):
            if _is_recipe_file(path):
                yield path


def validate_recipe_structure(food_dir: Path, output_path: Path | None = None, markdown_path: Path | None = None) -> tuple[Path, Path | None]:
    food_dir = food_dir.resolve()
    if output_path is None:
        output_path = food_dir / "recipe_validation.json"
    else:
        output_path = output_path.resolve()

    if markdown_path is None:
        markdown_path = food_dir / "recipe_validation.md"
    else:
        markdown_path = markdown_path.resolve()
    
    # Get database path from data directory
    db_path = Path(__file__).resolve().parents[3] / "data" / "recipes_local.db"
    
    # Connect to SQLite database
    conn = sqlite3.connect(db_path)
    
    try:
        recipes: list[dict[str, object]] = []
        
        # Get all recipes from database with their IDs
        cursor = conn.execute("""
            SELECT id, name, source_path, tags, servings, time_to_prepare, 
                   prepping, freezing_notes, reheat_notes, combinations, notes
            FROM recipes
            ORDER BY name
        """)
        
        for row in cursor.fetchall():
            recipe_id, name, source_path, tags, servings, time_to_prepare, \
                prepping, freezing_notes, reheat_notes, combinations, notes = row
            
            # Get actual file path from database source_path or use default
            if source_path:
                recipe_path = food_dir / source_path
            else:
                # Fallback to using the name in a normal way 
                # (this would only happen for inconsistent data)
                category_name = "unknown"
                filename = f"{name.replace(' ', '_')}.md"
                recipe_path = food_dir / category_name / filename
                
            if not recipe_path.exists():
                recipe_path = food_dir / source_path if source_path else None
                
            content = recipe_path.read_text(encoding="utf-8") if recipe_path and recipe_path.exists() else ""
            issues: list[str] = []

            if not content.lstrip().startswith("# "):
                issues.append("missing title heading")

            missing_metadata = [name for name in REQUIRED_METADATA if f"**{name}:**" not in content]
            if missing_metadata:
                issues.append("missing metadata: " + ", ".join(missing_metadata))

            missing_sections = [section for section in REQUIRED_SECTIONS if section not in content]
            if missing_sections:
                issues.append("missing required section: " + ", ".join(missing_sections))

            recipes.append(
                {
                    "id": recipe_id,
                    "path": source_path,
                    "filename": Path(source_path).name if source_path else "",
                    "category": Path(source_path).parent.name if source_path else "",
                    "valid": not issues,
                    "issues": issues,
                }
            )

        payload = {
            "generated_by": "validate_recipe_structure.py",
            "food_dir": food_dir.as_posix(),
            "summary": {
                "total_recipes": len(recipes),
                "valid_recipes": sum(1 for recipe in recipes if recipe["valid"]),
                "invalid_recipes": sum(1 for recipe in recipes if not recipe["valid"]),
            },
            "recipes": recipes,
        }

        output_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

        lines = [
            "# Recipe Validation",
            "",
            "This file is generated by the recipe structure validator.",
            "",
            f"- Total recipes: {payload['summary']['total_recipes']}",
            f"- Valid recipes: {payload['summary']['valid_recipes']}",
            f"- Invalid recipes: {payload['summary']['invalid_recipes']}",
            "",
        ]

        for recipe in recipes:
            status = "PASS" if recipe["valid"] else "FAIL"
            lines.append(f"## {status} - {recipe['path']}")
            if recipe["issues"]:
                for issue in recipe["issues"]:
                    lines.append(f"- {issue}")
            lines.append("")

        markdown_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    finally:
        conn.close()

    return output_path, markdown_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Validate recipe markdown structure against a simple schema.")
    parser.add_argument(
        "--food-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "food",
        help="Path to the food directory to scan",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output path for the generated JSON validation report",
    )
    parser.add_argument(
        "--markdown-output",
        type=Path,
        default=None,
        help="Optional output path for the generated markdown validation report",
    )
    args = parser.parse_args()

    output_path, markdown_path = validate_recipe_structure(args.food_dir, args.output, args.markdown_output)
    print(f"Recipe validation report written to {output_path}")
    if markdown_path is not None:
        print(f"Recipe validation markdown written to {markdown_path}")
