from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Iterable

def generate_nutrition_analytics(
    food_dir: Path,
    recipe_ids: list[int] | None = None,
    output_path: Path | None = None,
    markdown_path: Path | None = None,
) -> tuple[Path, Path | None]:
    """Generate nutrition analytics dashboard for selected recipes.

    Args:
        food_dir: Path to the food directory
        recipe_ids: List of recipe IDs to include in analytics (all if None)
        output_path: Optional output path for JSON analytics
        markdown_path: Optional output path for markdown analytics

    Returns:
        Tuple of (JSON output path, markdown output path)
    """
    food_dir = food_dir.resolve()
    if output_path is None:
        output_path = food_dir / "nutrition_analytics.json"
    else:
        output_path = output_path.resolve()

    if markdown_path is None:
        markdown_path = food_dir / "nutrition_analytics.md"
    else:
        markdown_path = markdown_path.resolve()
    
    # Get database path from data directory
    db_path = Path(__file__).resolve().parents[3] / "data" / "recipes_local.db"
    
    # Connect to SQLite database
    conn = sqlite3.connect(db_path)
    
    try:
        # Get all recipes with their details
        if recipe_ids is None:
            cursor = conn.execute("""
                SELECT id, name, servings, tags, time_to_prepare 
                FROM recipes 
                ORDER BY name
            """)
        else:
            placeholders = ','.join('?' * len(recipe_ids))
            cursor = conn.execute(f"""
                SELECT id, name, servings, tags, time_to_prepare 
                FROM recipes 
                WHERE id IN ({placeholders})
                ORDER BY name
            """, recipe_ids)
        
        recipes = []
        for row in cursor.fetchall():
            recipe_id, name, servings, tags, time_to_prepare = row
            
            # Get tags as a list
            tags_list = tags.split(",") if tags else []
            
            recipes.append({
                "id": recipe_id,
                "name": name,
                "servings": servings or 1,
                "tags": tags_list,
                "time_to_prepare": time_to_prepare or 0
            })
        
        # Generate analytics
        total_recipes = len(recipes)
        serving_totals = sum(r["servings"] for r in recipes)
        avg_time = sum(r["time_to_prepare"] for r in recipes) / max(len(recipes), 1)
        
        # Analyze tags (dietary preferences)
        tag_counts = {}
        for recipe in recipes:
            for tag in recipe["tags"]:
                tag_clean = tag.strip().lower()
                if tag_clean:
                    tag_counts[tag_clean] = tag_counts.get(tag_clean, 0) + 1
        
        # Analyze recipe categories
        categories = {
            "high-protein": 0,
            "vegetarian": 0,
            "low-carb": 0,
            "gluten-free": 0,
            "dairy-free": 0,
            "keto": 0,
            "freezer-friendly": 0
        }
        
        for recipe in recipes:
            for tag in recipe["tags"]:
                tag_clean = tag.strip().lower()
                if "protein" in tag_clean:
                    categories["high-protein"] += 1
                elif any(word in tag_clean for word in ["vegetarian", "veggie", "plant-based"]):
                    categories["vegetarian"] += 1
                elif "low-carb" in tag_clean:
                    categories["low-carb"] += 1
                elif "gluten-free" in tag_clean:
                    categories["gluten-free"] += 1
                elif "dairy-free" in tag_clean:
                    categories["dairy-free"] += 1
                elif "keto" in tag_clean:
                    categories["keto"] += 1
                elif "freezer-friendly" in tag_clean:
                    categories["freezer-friendly"] += 1

        analytics = {
            "generated_by": "nutrition_analytics.py",
            "analysis_date": "2026-07-13",  # Static for this project's context
            "total_recipes": total_recipes,
            "total_servings": serving_totals,
            "average_prep_time_minutes": round(avg_time, 1),
            "recipe_categories": categories,
            "tag_distribution": tag_counts,
            "recipes_included": recipes
        }

        # Write JSON output
        output_path.write_text(json.dumps(analytics, indent=2) + "\n", encoding="utf-8")

        # Write markdown summary
        lines = [
            "# Nutrition Analytics Dashboard",
            "",
            f"Generated by: nutrition_analytics.py",
            f"Analysis Date: {analytics['analysis_date']}",
            f"- Total recipes analyzed: {analytics['total_recipes']}",
            f"- Total servings available: {analytics['total_servings']}",
            f"- Average prep time: {analytics['average_prep_time_minutes']} minutes",
            "",
            "## Recipe Categories",
            ""
        ]
        
        for category, count in analytics["recipe_categories"].items():
            lines.append(f"- **{category}**: {count} recipes")
        lines.append("")
        
        lines.append("## Tag Distribution")
        for tag, count in sorted(analytics["tag_distribution"].items()):
            lines.append(f"- **{tag}**: {count} occurrences")
        lines.append("")
        
        lines.append("## Included Recipes")
        for recipe in analytics["recipes_included"]:
            tags_str = ", ".join(recipe["tags"]) if recipe["tags"] else "None"
            lines.append(f"- **{recipe['name']}** ({recipe['servings']} servings)")
            lines.append(f"  Tags: {tags_str}")
            lines.append("")
            
        markdown_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    finally:
        conn.close()

    return output_path, markdown_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate nutrition analytics for recipes.")
    parser.add_argument(
        "--food-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "food",
        help="Path to the food directory to scan",
    )
    parser.add_argument(
        "--recipes",
        type=int,
        nargs="+",
        help="Recipe IDs to include in analytics (all if not specified)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output path for the generated JSON analytics",
    )
    parser.add_argument(
        "--markdown-output",
        type=Path,
        default=None,
        help="Optional output path for the generated markdown analytics",
    )
    args = parser.parse_args()

    output_path, markdown_path = generate_nutrition_analytics(
        args.food_dir,
        args.recipes,
        args.output,
        args.markdown_output,
    )
    print(f"Nutrition analytics written to {output_path}")
    if markdown_path is not None:
        print(f"Nutrition analytics markdown written to {markdown_path}")