-- generated by src/scripts/recipes/generate_localization_seed.py
-- do not edit by hand; update localization metadata json and regenerate

INSERT OR REPLACE INTO recipe_translations (recipe_id, language, name, tags, notes, prepping, translation_version, content_hash, provenance, updated_at_utc) VALUES
(2, 'en', 'Salsa Verde Chicken', 'high-protein, freezer-friendly', 'Fresh and versatile chicken base for meal prep.', 'Cook chicken with tomato, onion, garlic, chili, then finish with cilantro and lime.', 1, '4ec1d15032f8900ba1e49f566f423a6f9efb6fa8a779223c1456f075c7e4c8b0', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(2, 'pt', 'Frango Salsa Verde', 'alto-proteina, congelador', 'Base fresca e versatil para meal prep.', 'Cozinhar o frango com tomate, cebola, alho e malagueta, terminar com coentros e lima.', 1, 'f489ac976ce4f6d34e3a418f247f1f35cd6033d0e61d880bc4900cf5073bf44b', 'phase3-seed-generator', '2026-08-01T00:00:00Z');

INSERT OR REPLACE INTO ingredient_translations (ingredient_id, language, name, unit, translation_version, content_hash, provenance, updated_at_utc) VALUES
(2, 'en', 'onion', 'unit', 1, 'e630e795d72ce171fc84585883735b72f965cd339a67584869214e34494d6a33', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(2, 'pt', 'cebola', 'g', 1, 'b58da4b98027bb54790d875709438d75d2cdd0b0054039ddb39712f6143267df', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(3, 'en', 'garlic', 'clove', 1, '5b7486f5ef83dfc52c427ff0a73c30ba18cc34f5266adfe85f2014db358eded7', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(3, 'pt', 'alho', 'g', 1, 'ae98dcc452bffc275ad7ff86a501f7037dc7de15d133345c3d7254ec33b14fd5', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(6, 'en', 'salt', 'pinch', 1, '6cce8236a4da8e161b897be740974390481a9860ad45ba9e83dedbe8ea856302', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(6, 'pt', 'sal', 'g', 1, '00cc802d8cf87f9a146e8d81279ef178b6030da7d90c35bb16f3ac79b5f03dc9', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(7, 'en', 'pepper', 'pinch', 1, '72550397fcbc25f8d0ce31d38440dd47f5cce69146a5fee73eda7b453da21d78', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(7, 'pt', 'pimenta', 'g', 1, 'f71514dd2d6b2f55e6524627b91ae36c87fe5dea049a5ee1fbe49fd91256554a', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(8, 'en', 'olive oil', 'tbsp', 1, '5b7a4fcc69950fc234934418b6bc4b66e7187a50c6a2130fa3bc3e8825863a77', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(8, 'pt', 'azeite', 'ml', 1, 'c200de33b825b4a9daf2dee093aac273169993a0a1219c8a80e849ef23315064', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(9, 'en', 'chicken thigh', 'piece', 1, 'b5d70b20de72a8d39bd946d28322fb171af7abd5dc1ef7e1530c3b6e5f24a714', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(9, 'pt', 'frango', 'g', 1, 'fe1057abe976e62ccd7d98ef7fee7b39550c56b9fed03da5961f8e48143473dd', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(10, 'en', 'tomato', 'unit', 1, '199077fde2f7145cbf43a678c6699d7e44ebbe14b76fb020ded18114fc55b483', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(10, 'pt', 'tomate', 'g', 1, '46ce50c98980ca9ae293c47ac30a1bf8303be78bdb88460bb64b78b9d6cf4f3a', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(11, 'en', 'chili', 'unit', 1, '2ead22c9f0fff06df29c9fa05aa82708f8453446186e182f79bed39efa812e20', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(11, 'pt', 'malagueta', 'g', 1, '5dbbe4c61351166429b2c551814955c6701ade264fd16431c2f24f0973115c5e', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(12, 'en', 'fresh cilantro', 'tbsp', 1, '8348e0b6a73b876c5f59e09df32b3acee181e1f9abea0a1d3f74548edea674c8', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(12, 'pt', 'coentros frescos', 'g', 1, '3c258cde85d276e9abb50538147c73bc1189b27e4203a17bd67f344b93dbde66', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(13, 'en', 'lime juice', 'tbsp', 1, '8cbf41d03461e515ffbb72cd47b4aeaf415c79b67a07162792ad1b6ede2bb141', 'phase3-seed-generator', '2026-08-01T00:00:00Z'),
(13, 'pt', 'limao', 'ml', 1, 'b61f9aa0c32125c30dcf2b99dd3d3542b16f8111e1a16e5473007acc78a6869e', 'phase3-seed-generator', '2026-08-01T00:00:00Z');

INSERT OR REPLACE INTO recipe_index_metadata (recipe_id, language_coverage, projection_fingerprint, projection_schema_version, projection_generated_at_utc) VALUES
(2, 'en,pt', 'phase3-salsa-verde-seed', 'phase3-localized-seed-v1', '2026-08-01T00:00:00Z');
