from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Iterable

def find_ingredient_substitutions(
    food_dir: Path,
    target_ingredients: list[str],
    output_path: Path | None = None,
    markdown_path: Path | None = None,
) -> tuple[Path, Path | None]:
    """Find suitable ingredient substitutions for target ingredients.

    Args:
        food_dir: Path to the food directory
        target_ingredients: List of ingredient names to find substitutions for
        output_path: Optional output path for JSON substitutions
        markdown_path: Optional output path for markdown substitutions

    Returns:
        Tuple of (JSON output path, markdown output path)
    """
    food_dir = food_dir.resolve()
    if output_path is None:
        output_path = food_dir / "ingredient_substitutions.json"
    else:
        output_path = output_path.resolve()

    if markdown_path is None:
        markdown_path = food_dir / "ingredient_substitutions.md"
    else:
        markdown_path = markdown_path.resolve()
    
    # Get database path from data directory
    db_path = Path(__file__).resolve().parents[3] / "data" / "recipes_local.db"
    
    # Connect to SQLite database
    conn = sqlite3.connect(db_path)
    
    try:
        substitutions = {
            "generated_by": "ingredient_substitution_finder.py",
            "target_ingredients": target_ingredients,
            "substitutions": []
        }

        # Get all ingredients from database
        cursor = conn.execute("SELECT id, name FROM ingredients ORDER BY name")
        all_ingredients = {row[0]: row[1].lower() for row in cursor.fetchall()}
        
        # For each target ingredient, find related ingredients
        for target in target_ingredients:
            target_lower = target.lower()
            
            # Find potential substitutions (ingredient names that are similar or have common tags)
            candidate_substitutions = []
            
            # Look for ingredients with similar names
            for ing_id, ing_name in all_ingredients.items():
                if target_lower in ing_name or ing_name in target_lower:
                    # Don't include the target itself
                    if ing_name != target_lower:
                        candidate_substitutions.append({
                            "ingredient": ing_name,
                            "id": ing_id,
                            "confidence": "high" if target_lower == ing_name else "medium"
                        })
            
            # Also look for ingredients that appear in similar recipes (based on tags)
            # Query recipes that contain the target ingredient
            cursor = conn.execute("""
                SELECT DISTINCT r.id, r.name, r.tags
                FROM recipes r
                JOIN recipe_ingredients ri ON r.id = ri.recipe_id
                JOIN ingredients i ON ri.ingredient_id = i.id
                WHERE i.name LIKE ?
                ORDER BY r.name
            """, (f"%{target}%",))
                
            target_recipes = cursor.fetchall()
            
            # Find other ingredients in those recipes
            related_ingredients = set()
            for recipe_id, _, _ in target_recipes:
                cursor = conn.execute("""
                    SELECT i.name
                    FROM recipe_ingredients ri
                    JOIN ingredients i ON ri.ingredient_id = i.id
                    WHERE ri.recipe_id = ?
                """, (recipe_id,))
                
                for row in cursor.fetchall():
                    related_ingredient = row[0].lower()
                    if related_ingredient != target_lower:
                        related_ingredients.add(related_ingredient)
            
            # Add these to substitutions with lower confidence
            for ing_name in related_ingredients:
                if ing_name not in [sub["ingredient"] for sub in candidate_substitutions]:
                    candidate_substitutions.append({
                        "ingredient": ing_name,
                        "id": -1,  # Not in database
                        "confidence": "low"
                    })
            
            substitutions["substitutions"].append({
                "target": target,
                "candidates": candidate_substitutions[:5]  # Limit to top 5
            })

        # Write JSON output
        output_path.write_text(json.dumps(substitutions, indent=2) + "\n", encoding="utf-8")

        # Write markdown summary
        lines = [
            "# Ingredient Substitution Finder",
            "",
            f"Generated by: ingredient_substitution_finder.py",
            "This report suggests ingredient substitutions for the specified ingredients.",
            "",
        ]
        
        for item in substitutions["substitutions"]:
            lines.append(f"## Substitutes for {item['target']}")
            if not item['candidates']:
                lines.append("No suitable substitutes found.")
            else:
                for candidate in item['candidates']:
                    lines.append(f"- **{candidate['ingredient']}** ({candidate['confidence']} confidence)")
            lines.append("")
            
        markdown_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    finally:
        conn.close()

    return output_path, markdown_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Find ingredient substitutions for target ingredients.")
    parser.add_argument(
        "--food-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "food",
        help="Path to the food directory to scan",
    )
    parser.add_argument(
        "--ingredients",
        type=str,
        nargs="+",
        required=True,
        help="Target ingredient names to find substitutions for",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output path for the generated JSON substitutions",
    )
    parser.add_argument(
        "--markdown-output",
        type=Path,
        default=None,
        help="Optional output path for the generated markdown substitutions",
    )
    args = parser.parse_args()

    output_path, markdown_path = find_ingredient_substitutions(
        args.food_dir,
        args.ingredients,
        args.output,
        args.markdown_output,
    )
    print(f"Ingredient substitutions written to {output_path}")
    if markdown_path is not None:
        print(f"Ingredient substitutions markdown written to {markdown_path}")